name: Cron - Migrate DB from legacy server to RDS instance

on:
  # Every night around 1AM
  #schedule:
  #  - cron: "58 1 * * *"

  workflow_dispatch:

jobs:
  open-rds-to-external-connexion:
    uses: ./.github/workflows/apply.terraform.yml
    with:
      open-db-to-public-internet: "true"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  migrate-db:
    needs:
      - open-rds-to-external-connexion
    uses: ./.github/workflows/_orientdb-to-postgresql.reusable.yml
    secrets:
      DUMP_FILENAME: ${{ secrets.DUMP_FILENAME }}
      ORIENTDB_DBLOGIN: ${{ secrets.ORIENTDB_DBLOGIN }}
      ORIENTDB_DBNAME: ${{ secrets.ORIENTDB_DBNAME }}
      ORIENTDB_DBPASSWORD: ${{ secrets.ORIENTDB_DBPASSWORD }}
      SSH_LEGACY_SERVER_PASSWORD: ${{ secrets.SSH_LEGACY_SERVER_PASSWORD }}
      LEGACY_SERVER_USER: ${{ secrets.LEGACY_SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      LEGACY_SERVER_HOST: ${{ secrets.LEGACY_SERVER_HOST }}
      LEGACY_SERVER_PORT: ${{ secrets.LEGACY_SERVER_PORT }}
      LEGACY_SERVER_FINGERPRINT: ${{ secrets.LEGACY_SERVER_FINGERPRINT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PG_RDS_CONNEXION_STRING: ${{ secrets.PG_RDS_CONNEXION_STRING }}

  close-rds-to-external-connexion:
    needs:
      - migrate-db
    uses: ./.github/workflows/apply.terraform.yml
    with:
      open-db-to-public-internet: "false"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}